"""voice_messages table

Revision ID: 8d208fabd07a
Revises: d1a00004kb
Create Date: 2026-04-18 15:23:32.513045+00:00

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '8d208fabd07a'
down_revision: Union[str, None] = 'd1a00004kb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('voice_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tg_message_id', sa.BigInteger(), nullable=False),
    sa.Column('tg_user_id', sa.BigInteger(), nullable=False),
    sa.Column('chat_id', sa.BigInteger(), nullable=False),
    sa.Column('duration_sec', sa.Integer(), nullable=True),
    sa.Column('mime_type', sa.Text(), nullable=True),
    sa.Column('file_size_bytes', sa.Integer(), nullable=True),
    sa.Column('ogg_data', sa.LargeBinary(), nullable=False),
    sa.Column('transcribed_text', sa.Text(), nullable=True),
    sa.Column('transcribed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('analyzed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_voice_messages_chat_id'), 'voice_messages', ['chat_id'], unique=False)
    op.create_index(op.f('ix_voice_messages_created_at'), 'voice_messages', ['created_at'], unique=False)
    op.create_index(op.f('ix_voice_messages_tg_message_id'), 'voice_messages', ['tg_message_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_voice_messages_tg_message_id'), table_name='voice_messages')
    op.drop_index(op.f('ix_voice_messages_created_at'), table_name='voice_messages')
    op.drop_index(op.f('ix_voice_messages_chat_id'), table_name='voice_messages')
    op.drop_table('voice_messages')
    # ### end Alembic commands ###
