"""pending_ops table

Revision ID: 8fe3ebe5800f
Revises: b0f5e10ebf32
Create Date: 2026-04-18 11:07:13.644287+00:00

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '8fe3ebe5800f'
down_revision: Union[str, None] = 'b0f5e10ebf32'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pending_ops',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uid', sa.Text(), nullable=False),
    sa.Column('chat_id', sa.BigInteger(), nullable=False),
    sa.Column('preview_message_id', sa.BigInteger(), nullable=True),
    sa.Column('intent', sa.Text(), nullable=False),
    sa.Column('fields', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('source_message_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_by_tg_id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status IN ('pending','confirmed','cancelled','expired')", name='ck_pending_ops_status'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uid')
    )
    op.create_index(op.f('ix_pending_ops_chat_id'), 'pending_ops', ['chat_id'], unique=False)
    op.create_index(op.f('ix_pending_ops_created_at'), 'pending_ops', ['created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pending_ops_created_at'), table_name='pending_ops')
    op.drop_index(op.f('ix_pending_ops_chat_id'), table_name='pending_ops')
    op.drop_table('pending_ops')
    # ### end Alembic commands ###
