"""seen_stickers table

Revision ID: b0f5e10ebf32
Revises: c1a00002seed
Create Date: 2026-04-18 10:39:38.811180+00:00

"""
from __future__ import annotations

from typing import Union
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = 'b0f5e10ebf32'
down_revision: str | None = 'c1a00002seed'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('seen_stickers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('file_id', sa.Text(), nullable=False),
    sa.Column('file_unique_id', sa.Text(), nullable=True),
    sa.Column('sticker_set', sa.Text(), nullable=True),
    sa.Column('emoji', sa.Text(), nullable=True),
    sa.Column('is_animated', sa.Boolean(), nullable=False),
    sa.Column('is_video', sa.Boolean(), nullable=False),
    sa.Column('first_seen', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_used', sa.DateTime(timezone=True), nullable=True),
    sa.Column('usage_count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('file_id')
    )
    op.create_index(op.f('ix_seen_stickers_emoji'), 'seen_stickers', ['emoji'], unique=False)
    op.create_index(op.f('ix_seen_stickers_file_unique_id'), 'seen_stickers', ['file_unique_id'], unique=False)
    op.create_index(op.f('ix_seen_stickers_sticker_set'), 'seen_stickers', ['sticker_set'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_seen_stickers_sticker_set'), table_name='seen_stickers')
    op.drop_index(op.f('ix_seen_stickers_file_unique_id'), table_name='seen_stickers')
    op.drop_index(op.f('ix_seen_stickers_emoji'), table_name='seen_stickers')
    op.drop_table('seen_stickers')
    # ### end Alembic commands ###
