"""initial schema

Revision ID: b4fbd8da6908
Revises: 
Create Date: 2026-04-17 20:19:34.463004+00:00

"""
from __future__ import annotations

from typing import Union
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'b4fbd8da6908'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('few_shot_examples',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('intent', sa.Text(), nullable=False),
    sa.Column('input_text', sa.Text(), nullable=False),
    sa.Column('parsed_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('verified', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('used_count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_few_shot_examples_intent'), 'few_shot_examples', ['intent'], unique=False)
    op.create_table('message_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tg_message_id', sa.BigInteger(), nullable=True),
    sa.Column('tg_user_id', sa.BigInteger(), nullable=True),
    sa.Column('chat_id', sa.BigInteger(), nullable=False),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('has_media', sa.Boolean(), nullable=False),
    sa.Column('is_bot', sa.Boolean(), nullable=False),
    sa.Column('is_mention', sa.Boolean(), nullable=False),
    sa.Column('intent_detected', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_message_log_chat_id'), 'message_log', ['chat_id'], unique=False)
    op.create_index(op.f('ix_message_log_tg_message_id'), 'message_log', ['tg_message_id'], unique=False)
    op.create_index(op.f('ix_message_log_tg_user_id'), 'message_log', ['tg_user_id'], unique=False)
    op.create_table('partners',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('tg_user_id', sa.BigInteger(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('tg_user_id')
    )
    op.create_table('pending_reminders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reminder_type', sa.Text(), nullable=False),
    sa.Column('due_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('fired', sa.Boolean(), nullable=False),
    sa.Column('fired_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('context', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pending_reminders_reminder_type'), 'pending_reminders', ['reminder_type'], unique=False)
    op.create_table('prepayments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('amount_rub', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('amount_usdt', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('fx_rate', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('supplier', sa.Text(), nullable=True),
    sa.Column('given_date', sa.Date(), nullable=False),
    sa.Column('expected_cabinets', sa.Integer(), nullable=True),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('pending','fulfilled','partial','cancelled')", name='ck_prepayments_status'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('wallets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('currency', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.CheckConstraint("currency IN ('RUB','USDT')", name='ck_wallets_currency'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('cabinets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('auto_code', sa.Text(), nullable=False),
    sa.Column('cost_rub', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('cost_usdt', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('fx_rate', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('received_date', sa.Date(), nullable=False),
    sa.Column('prepayment_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('in_use_since', sa.DateTime(timezone=True), nullable=True),
    sa.Column('worked_out_date', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('in_stock','in_use','worked_out','blocked','recovered','lost')", name='ck_cabinets_status'),
    sa.ForeignKeyConstraint(['prepayment_id'], ['prepayments.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('auto_code')
    )
    op.create_table('partner_contributions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('partner_id', sa.Integer(), nullable=False),
    sa.Column('source', sa.Text(), nullable=False),
    sa.Column('source_ref_id', sa.Integer(), nullable=True),
    sa.Column('amount_usdt', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('contribution_date', sa.Date(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("source IN ('initial_depo','poa_share','manual')", name='ck_partner_contributions_source'),
    sa.ForeignKeyConstraint(['partner_id'], ['partners.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('partner_withdrawals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('partner_id', sa.Integer(), nullable=False),
    sa.Column('amount_usdt', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('withdrawal_date', sa.Date(), nullable=False),
    sa.Column('from_wallet_id', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['from_wallet_id'], ['wallets.id'], ),
    sa.ForeignKeyConstraint(['partner_id'], ['partners.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tg_user_id', sa.BigInteger(), nullable=False),
    sa.Column('tg_username', sa.Text(), nullable=True),
    sa.Column('display_name', sa.Text(), nullable=True),
    sa.Column('role', sa.Text(), nullable=False),
    sa.Column('partner_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("role IN ('partner','assistant','viewer')", name='ck_users_role'),
    sa.ForeignKeyConstraint(['partner_id'], ['partners.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tg_user_id')
    )
    op.create_table('audit_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.Text(), nullable=False),
    sa.Column('table_name', sa.Text(), nullable=False),
    sa.Column('record_id', sa.Integer(), nullable=True),
    sa.Column('old_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('new_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('exchanges',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('amount_rub', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('amount_usdt', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('fx_rate', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('exchange_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('raw_input', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('expenses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category', sa.Text(), nullable=False),
    sa.Column('amount_rub', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('amount_usdt', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('fx_rate', sa.Numeric(precision=18, scale=8), nullable=True),
    sa.Column('expense_date', sa.Date(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('feedback',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('context', sa.Text(), nullable=True),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('new','noted','in_progress','done','wontdo')", name='ck_feedback_status'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('knowledge_base',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category', sa.Text(), nullable=False),
    sa.Column('key', sa.Text(), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('confidence', sa.Text(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_used', sa.DateTime(timezone=True), nullable=True),
    sa.Column('usage_count', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.CheckConstraint("category IN ('entity','rule','pattern','preference','glossary','alias')", name='ck_knowledge_base_category'),
    sa.CheckConstraint("confidence IN ('confirmed','inferred','tentative')", name='ck_knowledge_base_confidence'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_knowledge_base_key'), 'knowledge_base', ['key'], unique=False)
    op.create_table('poa_withdrawals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('amount_rub', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('amount_usdt', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('fx_rate', sa.Numeric(precision=18, scale=8), nullable=True),
    sa.Column('client_share_pct', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('partner_shares', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('client_debt_usdt', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('client_paid', sa.Boolean(), nullable=False),
    sa.Column('client_paid_date', sa.Date(), nullable=True),
    sa.Column('withdrawal_date', sa.Date(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('cabinets_worked', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('acquiring_today', sa.Boolean(), nullable=True),
    sa.Column('total_wallets', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('total_assets', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('total_liabilities', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('net_profit', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('raw_output', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fx_rates_snapshot',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('from_ccy', sa.Text(), nullable=False),
    sa.Column('to_ccy', sa.Text(), nullable=False),
    sa.Column('rate', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('rate_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source_exchange_id', sa.Integer(), nullable=True),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['source_exchange_id'], ['exchanges.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('wallet_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('report_id', sa.Integer(), nullable=True),
    sa.Column('wallet_id', sa.Integer(), nullable=False),
    sa.Column('amount_native', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('amount_usdt', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('fx_rate', sa.Numeric(precision=18, scale=8), nullable=True),
    sa.Column('snapshot_time', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['report_id'], ['reports.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['wallet_id'], ['wallets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('wallet_snapshots')
    op.drop_table('fx_rates_snapshot')
    op.drop_table('reports')
    op.drop_table('poa_withdrawals')
    op.drop_index(op.f('ix_knowledge_base_key'), table_name='knowledge_base')
    op.drop_table('knowledge_base')
    op.drop_table('feedback')
    op.drop_table('expenses')
    op.drop_table('exchanges')
    op.drop_table('audit_log')
    op.drop_table('users')
    op.drop_table('partner_withdrawals')
    op.drop_table('partner_contributions')
    op.drop_table('cabinets')
    op.drop_table('wallets')
    op.drop_table('prepayments')
    op.drop_index(op.f('ix_pending_reminders_reminder_type'), table_name='pending_reminders')
    op.drop_table('pending_reminders')
    op.drop_table('partners')
    op.drop_index(op.f('ix_message_log_tg_user_id'), table_name='message_log')
    op.drop_index(op.f('ix_message_log_tg_message_id'), table_name='message_log')
    op.drop_index(op.f('ix_message_log_chat_id'), table_name='message_log')
    op.drop_table('message_log')
    op.drop_index(op.f('ix_few_shot_examples_intent'), table_name='few_shot_examples')
    op.drop_table('few_shot_examples')
    op.drop_table('clients')
    # ### end Alembic commands ###
